name       : udisks
version    : 2.8.4
release    : 24
source     :
    - https://github.com/storaged-project/udisks/releases/download/udisks-2.8.4/udisks-2.8.4.tar.bz2 : d28367bdacfa039719327e68300b6118427874f2dc53ff7109dedb70a7289819
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Daemon, tools and libraries to access disks and storage devices
description: |
    The UDisks package provides a daemon, tools and libraries to access and manipulate disks and storage devices.
builddeps  :
    - pkgconfig(blockdev)
    - pkgconfig(devmapper)
    - pkgconfig(libatasmart)
    - pkgconfig(libattr)
    - acl-devel
rundeps    :
    - cryptsetup
    - exfatprogs
    - gptfdisk
    - mdadm
setup      : |
    %patch -p1 -i $pkgfiles/0001-fix-test.patch
    %patch -p1 -i $pkgfiles/0002-support-exfatprogs.patch
    %configure --disable-static \
               --enable-introspection \
               --with-udevdir=%libdir%/udev \
               --with-modprobedir=%libdir%/modprobe.d \
               --disable-man \
               --enable-lvm2 \
               --enable-lvmcache
build      : |
    %make
install    : |
    %make_install
    # Polkit rules file
    install -Dm00644 $pkgfiles/org.freedesktop.UDisks2.rules $installdir/usr/share/polkit-1/rules.d/org.freedesktop.UDisks2.rules

    # Do not ship /var/lib in package
    rm -rfv $installdir/var
check      : |
    %make check
