name       : udisks
version    : 2.1.8
release    : 12
source     :
    - https://udisks.freedesktop.org/releases/udisks-2.1.8.tar.bz2 : da416914812a77e5f4d82b81deb8c25799fd3228d27d52f7bf89a501b1857dda
license    :
    - GPL-2.0
summary    : Daemon, tools and libraries to access disks and storage devices
component  : desktop.core
builddeps  :
    - pkgconfig(libatasmart)
    - pkgconfig(gudev-1.0)
    - pkgconfig(gio-unix-2.0)
    - acl-devel
    - attr-devel
rundeps    :
    - cryptsetup
description: |
    The UDisks package provides a daemon, tools and libraries to access and manipulate disks and storage devices.
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --with-udevdir=%libdir%/udev \
               --disable-man
build      : |
    %make
install    : |
    %make_install
