name       : udisks
version    : 2.10.0
release    : 25
source     :
    - https://github.com/storaged-project/udisks/releases/download/udisks-2.10.0/udisks-2.10.0.tar.bz2 : 4f5a7a592526f7f32795a1f2211c67b9a649ab40386752f9a71ebaa2fc2090bc
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Daemon, tools and libraries to access disks and storage devices
description: |
    The UDisks package provides a daemon, tools and libraries to access and manipulate disks and storage devices.
builddeps  :
    - pkgconfig(blockdev)
    - pkgconfig(devmapper)
    - pkgconfig(libatasmart)
    - pkgconfig(libattr)
    - acl-devel
rundeps    :
    - cryptsetup
    - exfatprogs
    - gptfdisk
    - mdadm
setup      : |
    %patch -p1 -i $pkgfiles/0001-Add-support-for-a-stateless-configuration-file.patch
    %configure --disable-static \
               --enable-introspection \
               --with-udevdir=%libdir%/udev \
               --with-modprobedir=%libdir%/modprobe.d \
               --disable-man \
               --enable-btrfs \
               --enable-lvm2
build      : |
    %make
install    : |
    %make_install
    # Polkit rules file
    install -Dm00644 $pkgfiles/org.freedesktop.UDisks2.rules $installdir/usr/share/polkit-1/rules.d/org.freedesktop.UDisks2.rules

    # Stateless
    install -D udisks/udisks2.conf $installdir/usr/share/defaults/etc/udisks2/udisks2.conf
    rm -v $installdir/etc/udisks2/mount_options.conf.example \
          $installdir/etc/udisks2/udisks2.conf
    rmdir -v $installdir/etc/udisks2 \
             $installdir/etc \
             $installdir/var/lib/udisks2 \
             $installdir/var/lib \
             $installdir/var
check      : |
    %make check
