name       : udisks
version    : 2.7.4
release    : 16
source     :
    - https://github.com/storaged-project/udisks/releases/download/udisks-2.7.4/udisks-2.7.4.tar.bz2 : 4b8db9f1c5410f079c5d06e4229e233371413fa98f20f05107819957258bc199
license    : GPL-2.0
component  : desktop.core
summary    : Daemon, tools and libraries to access disks and storage devices
description: |
    The UDisks package provides a daemon, tools and libraries to access and manipulate disks and storage devices.
builddeps  :
    - pkgconfig(blockdev)
    - pkgconfig(devmapper)
    - pkgconfig(libatasmart)
    - acl-devel
    - attr-devel
rundeps    :
    - cryptsetup
    - gptfdisk
    - mdadm
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --with-udevdir=%libdir%/udev \
               --with-modprobedir=%libdir%/modprobe.d \
               --disable-man \
               --enable-lvm2 \
               --enable-lvmcache
build      : |
    %make
install    : |
    %make_install
    # support keyfile backend in udisks
    install -D -m 00644 $pkgfiles/udisks2.keyrules $installdir/usr/share/polkit-1/rules.d/udisks2.keyrules

    # Do not ship /var/lib in package
    rm -rfv $installdir/var
    install -D -m 00644 $pkgfiles/udisks2.tmpfiles $installdir/%libdir%/tmpfiles.d/udisks2.conf

check      : |
    %make check
