name       : udisks
version    : 2.7.2
release    : 14
source     :
    - https://github.com/storaged-project/udisks/releases/download/udisks-2.7.2/udisks-2.7.2.tar.bz2 : 861964e6dd4cd1d814ad801c3042c8be748fddeb2970737132e2aff500c0d815
license    : GPL-2.0
component  : desktop.core
summary    : Daemon, tools and libraries to access disks and storage devices
description: |
    The UDisks package provides a daemon, tools and libraries to access and manipulate disks and storage devices.
builddeps  :
    - pkgconfig(blockdev)
    - pkgconfig(devmapper)
    - pkgconfig(libatasmart)
    - acl-devel
    - attr-devel
rundeps    :
    - cryptsetup
    - gptfdisk
    - mdadm
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --with-udevdir=%libdir%/udev \
               --with-modprobedir=%libdir%/modprobe.d \
               --disable-man \
               --enable-lvm2 \
               --enable-lvmcache
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
