name       : udisks
version    : 2.6.5
release    : 13
source     :
    - https://github.com/storaged-project/udisks/releases/download/udisks-2.6.5/udisks-2.6.5.tar.bz2 : cbc3cd1600a39e168175b1f22bdda7bc9c3feea0f3ed0556001f8b23ee73a7d1
license    :
    - GPL-2.0
summary    : Daemon, tools and libraries to access disks and storage devices
component  : desktop.core
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(libatasmart)
    - pkgconfig(gudev-1.0)
    - pkgconfig(gio-unix-2.0)
    - acl-devel
    - attr-devel
rundeps    :
    - cryptsetup
description: |
    The UDisks package provides a daemon, tools and libraries to access and manipulate disks and storage devices.
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --with-udevdir=%libdir%/udev \
               --disable-man \
               --enable-lvm2 \
               --enable-lvmcache
build      : |
    %make
install    : |
    %make_install
