name        : udisks
version     : 2.1.6
release     : 6
source     :
    - http://udisks.freedesktop.org/releases/udisks-2.1.6.tar.bz2 : dec5f5c85fa0f74f39336acbfba1770f9988c096be23873714543c304b09f46a
license     :
    - GPL-2.0
summary     : Daemon, tools and libraries to access disks and storage devices
builddeps   :
    - pkgconfig(libatasmart)
    - docbook-xsl
description : |
    The UDisks package provides a daemon, tools and libraries to access and manipulate disks and storage devices.
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --with-udevdir=/lib/udev \
               --disable-man
build      : |
    %make
install    : |
    %make_install
