name       : udisks
version    : 2.1.7
release    : 11
source     :
    - https://udisks.freedesktop.org/releases/udisks-2.1.7.tar.bz2 : abae2bb3bdc691ca13c1e4c244630b8c881c4f3b35c207299f1b39b7bec83785
license    :
    - GPL-2.0
summary    : Daemon, tools and libraries to access disks and storage devices
component  : desktop.core
builddeps  :
    - pkgconfig(libatasmart)
    - pkgconfig(gudev-1.0)
    - pkgconfig(gio-unix-2.0)
rundeps    :
    - cryptsetup
description: |
    The UDisks package provides a daemon, tools and libraries to access and manipulate disks and storage devices.
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --with-udevdir=%libdir%/udev \
               --disable-man
build      : |
    %make
install    : |
    %make_install
